# Calculate the total revenue generated by two product categories in a store 

import numpy as np 

category1_revenue = np.array([500,600,700,550])
category2_revenue = np.array([450,700,800,600])
total_revenue = category1_revenue + category2_revenue
print(" Total Revenue : " , total_revenue)

print("--------------------------------------------------------------------------------")

# Calculate the profit made by a company 

revenue = np.array([10000,12000,11000,10500])
expenses = np.array([4000,5000,4500,4800])
print("Profit : " , revenue - expenses)

print("--------------------------------------------------------------------------------")

# Determine which products in a store are out of stock (quantity is 0)

inventory = np.array([10,0,5,0,20,0])
print("Out of Stock Products : " , inventory[inventory == 0])

print("--------------------------------------------------------------------------------")

# Calculate the total cost of items in a shopping cart , considering the quantity and price per item.

quantity = np.array([2,3,4,1])
price_per_item = np.array([10.0 , 5.0 , 8.0 , 12.0])
print("Total Cost of items : " , quantity * price_per_item)